"""Public API for the quadratic_diagonal package.

This package provides exact constructive representability algorithms for
diagonal quadratic lattices over maximal real quadratic orders.
"""

__version__ = "0.2.0"

from .weighted_diagonal_exact import (
    Pair,
    RealQuadraticOrder,
    WeightedTraceForm,
    EnumerationStats,
    SearchResult,
    RepresentationResult,
    BoundedRepresentabilityResult,
    PreparedSingleTarget,
    PreparedBoundedValues,
    EnumerationBenchmarkRow,
    RepresentabilityBenchmarkRow,
    GenericBaselineBenchmarkRow,
    BoundedBenchmarkRow,
    OptimisationBenchmarkRow,
    BalancingBenchmarkRow,
    weighted_trace_form,
    exact_row_interval,
    discriminant_identity,
    enumerate_weighted_values_by_trace,
    enumerate_weighted_search,
    enumerate_weighted_search_box,
    diagonal_representability_dp,
    diagonal_representability_mitm,
    enumerate_totally_positive_targets,
    batched_bounded_representables,
    bounded_truants_batched,
    bounded_truants_naive,
    row_candidate_count_by_trace,
    sharp_box_candidate_count_by_trace,
    balancing_benchmark_row,
    benchmark_optimisation,
    benchmark_weighted_enumeration,
    benchmark_representability,
    benchmark_bounded_truants,
    benchmark_generic_baseline,
    format_pair,
)

__all__ = [
    '__version__',
    'Pair',
    'RealQuadraticOrder',
    'WeightedTraceForm',
    'EnumerationStats',
    'SearchResult',
    'RepresentationResult',
    'BoundedRepresentabilityResult',
    'PreparedSingleTarget',
    'PreparedBoundedValues',
    'EnumerationBenchmarkRow',
    'RepresentabilityBenchmarkRow',
    'GenericBaselineBenchmarkRow',
    'BoundedBenchmarkRow',
    'OptimisationBenchmarkRow',
    'BalancingBenchmarkRow',
    'weighted_trace_form',
    'exact_row_interval',
    'discriminant_identity',
    'enumerate_weighted_values_by_trace',
    'enumerate_weighted_search',
    'enumerate_weighted_search_box',
    'diagonal_representability_dp',
    'diagonal_representability_mitm',
    'enumerate_totally_positive_targets',
    'batched_bounded_representables',
    'bounded_truants_batched',
    'bounded_truants_naive',
    'row_candidate_count_by_trace',
    'sharp_box_candidate_count_by_trace',
    'balancing_benchmark_row',
    'benchmark_optimisation',
    'benchmark_weighted_enumeration',
    'benchmark_representability',
    'benchmark_bounded_truants',
    'benchmark_generic_baseline',
    'format_pair',
]
